<<<<<<< Updated upstream
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
=======
"use client";
import { Poppins } from 'next/font/google';
import { store } from "./redux/store";
import { Provider } from "react-redux";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

// export const metadata = {
//   title: "Ketchup Inc",
//   description: "Adding Flavor to Email!",
// };
>>>>>>> Stashed changes

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export default function RootLayout({ children }) {
  return (
    <GoogleOAuthProvider clientId="801064546104-59ceuepf5flhunktpf3f5876og9jlqrg.apps.googleusercontent.com">
<<<<<<< Updated upstream
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
=======
       <html className={`${poppins.variable}`}>
        <Provider store={store}>
        <body>{children}</body>
        </Provider>
      </html>
>>>>>>> Stashed changes
    </GoogleOAuthProvider>
  );
}
